version: 1.0.0
includes:
  - types:
      filter: tag == "view_type" && type != "health"
routes:
  - health:
      path: /api/health
      method: GET
      description: Liveness
      response: health
