version: 1.0.0
types:
  - user:
      tags: [datasource_type, view_type]
      inherits: set
      fields:
        - email:
            type: string
            size: 256
  - project:
      tags: [datasource_type, view_type]
      inherits: set
      fields:
        - name:
            type: string
            size: 128
        - owner_id:
            references: user.id
  - task:
      tags: [datasource_type, view_type]
      inherits: set
      fields:
        - title:
            type: string
            size: 256
        - done:
            type: boolean
            default_value: false
        - notes:
            type: string
            size: 1024
            is_nullable: true
        - project_id:
            references: project.id
  - health:
      tags: [view_type]
      fields:
        - ok:
            type: boolean
