version: 1.0.0
types:
  - legacy_user:
      tags: [datasource_type]
      fields:
        - old_email:
            type: string
            size: 128
        - legacy_flag:
            type: boolean
            default_value: false
        - bio:
            type: string
            size: 256
            is_nullable: true
